In [77]:
import numpy as np
from matplotlib import pyplot as plt
import plotly
from pathlib import Path

In [83]:
class Event():
    def __init__(self, input_path, prediction_path):
        self.input_path = input_path
        self.prediction_path = prediction_path
        self._load()
        
    def _load(self):
        input_event = np.load(self.input_path)
        event_prediction = np.load(self.prediction_path)
        self.labels = event_prediction['labels']
        self.prediction_probs = event_prediction['prediction']
        self.predictions = self.prediction_probs.argmax(axis=1)
        self.inds = event_prediction['inds']
        self.x = input_event['x'][self.inds]

In [79]:
wandb_id = '20200820173002'
wandb_project = 'hgcal-spvcnn'
wandb_entity = 'uw-hgcal'

In [80]:
input_dir = Path('/global/cscratch1/sd/schuya/hgcal-dev/data/hgcal/rawpointclouds')
prediction_dir = Path('/global/cscratch1/sd/schuya/hgcal-dev/predictions/20200820173002')

In [81]:
event_names = [a.name for a in sorted(prediction_dir.glob('*.npz'))]

In [84]:
events = [Event(input_dir / e, prediction_dir / e) for e in event_names]

In [96]:
all_predictions = np.concatenate([e.predictions for e in events])
all_labels = np.concatenate([e.labels for e in events])

In [98]:
np.unique(all_predictions, return_counts=True)

(array([0, 1, 2, 3]), array([19190395,   400324,   432756,     8980]))

In [99]:
np.unique(all_labels, return_counts=True)

(array([0, 1, 2, 3]), array([19149469,   437306,   436419,     9261]))

In [101]:
from sklearn.metrics import confusion_matrix

rows = true, cols = pred

In [103]:
conf_mat = confusion_matrix(all_labels, all_predictions)

In [110]:
norm_conf_mat = confusion_matrix(all_labels, all_predictions, normalize='true')

In [109]:
conf_mat

array([[19097503,    23330,    28359,      277],
       [   44888,   344234,    47681,      503],
       [   47502,    32199,   356709,        9],
       [     502,      561,        7,     8191]])

In [111]:
norm_conf_mat

array([[9.97286296e-01, 1.21831054e-03, 1.48092879e-03, 1.44651531e-05],
       [1.02646659e-01, 7.87169625e-01, 1.09033491e-01, 1.15022433e-03],
       [1.08844940e-01, 7.37800142e-02, 8.17354423e-01, 2.06223835e-05],
       [5.42058093e-02, 6.05766116e-02, 7.55857899e-04, 8.84461721e-01]])

In [116]:
np.set_printoptions(precision=2, suppress=True)

In [117]:
norm_conf_mat

array([[1.  , 0.  , 0.  , 0.  ],
       [0.1 , 0.79, 0.11, 0.  ],
       [0.11, 0.07, 0.82, 0.  ],
       [0.05, 0.06, 0.  , 0.88]])